// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW7LMoS2-6HvuDcMQ1wzl1iHjmcHVm-kw',
    appId: '1:919163114404:web:8b0723ccfd34759cf16731',
    messagingSenderId: '919163114404',
    projectId: 'hervoice-81bdf',
    authDomain: 'hervoice-81bdf.firebaseapp.com',
    databaseURL: 'https://hervoice-81bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hervoice-81bdf.firebasestorage.app',
    measurementId: 'G-L3G4QHZ06D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8g-02_Ba-9DG1wvH0xwkRGdWkRPNMF0Y',
    appId: '1:919163114404:android:54ce93cd9da610e7f16731',
    messagingSenderId: '919163114404',
    projectId: 'hervoice-81bdf',
    databaseURL: 'https://hervoice-81bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hervoice-81bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1he2Mw-eSeZkMXn6BuIzznofgoDObGTo',
    appId: '1:919163114404:ios:a470074ebec2a3fbf16731',
    messagingSenderId: '919163114404',
    projectId: 'hervoice-81bdf',
    databaseURL: 'https://hervoice-81bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hervoice-81bdf.firebasestorage.app',
    iosBundleId: 'com.example.herVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1he2Mw-eSeZkMXn6BuIzznofgoDObGTo',
    appId: '1:919163114404:ios:a470074ebec2a3fbf16731',
    messagingSenderId: '919163114404',
    projectId: 'hervoice-81bdf',
    databaseURL: 'https://hervoice-81bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hervoice-81bdf.firebasestorage.app',
    iosBundleId: 'com.example.herVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW7LMoS2-6HvuDcMQ1wzl1iHjmcHVm-kw',
    appId: '1:919163114404:web:12fd7d5e74e2b5f7f16731',
    messagingSenderId: '919163114404',
    projectId: 'hervoice-81bdf',
    authDomain: 'hervoice-81bdf.firebaseapp.com',
    databaseURL: 'https://hervoice-81bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hervoice-81bdf.firebasestorage.app',
    measurementId: 'G-PHZLYDNJKF',
  );

}